//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonGo.RocketAPI.Window.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokemonGo.RocketAPI.Window.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account: {0}.
        /// </summary>
        internal static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Area: .
        /// </summary>
        internal static string area {
            get {
                return ResourceManager.GetString("area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Argument Null Refference - Restarting.
        /// </summary>
        internal static string argument_null {
            get {
                return ResourceManager.GetString("argument_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to check for updates now....
        /// </summary>
        internal static string check_update_failed {
            get {
                return ResourceManager.GetString("check_update_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Country: .
        /// </summary>
        internal static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à , Eggs: {0}.
        /// </summary>
        internal static string eggs {
            get {
                return ResourceManager.GetString("eggs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to get Country/Place.
        /// </summary>
        internal static string error_country {
            get {
                return ResourceManager.GetString("error_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Evolved {0} pieces of {1} for {2}xp.
        /// </summary>
        internal static string evolve_pieces {
            get {
                return ResourceManager.GetString("evolve_pieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Evolved {0} successfully for {1}xp.
        /// </summary>
        internal static string evolve_success {
            get {
                return ResourceManager.GetString("evolve_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à , Gems: {0}.
        /// </summary>
        internal static string gems {
            get {
                return ResourceManager.GetString("gems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can find it at www.github.com/DetectiveSquirrel/Pokemon-Go-Rocket-API.
        /// </summary>
        internal static string github_link {
            get {
                return ResourceManager.GetString("github_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Github version is .
        /// </summary>
        internal static string github_version {
            get {
                return ResourceManager.GetString("github_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à , Items: {0}.
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Latitude: {0}.
        /// </summary>
        internal static string latitude {
            get {
                return ResourceManager.GetString("latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login Type: Google.
        /// </summary>
        internal static string login_type_Google {
            get {
                return ResourceManager.GetString("login_type_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login Type: Pokemon Trainers Club.
        /// </summary>
        internal static string login_type_PTC {
            get {
                return ResourceManager.GetString("login_type_PTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Longitude: {0}.
        /// </summary>
        internal static string longitude {
            get {
                return ResourceManager.GetString("longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name: {0}.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No nearby useful locations found. Please wait 10 seconds..
        /// </summary>
        internal static string no_location {
            get {
                return ResourceManager.GetString("no_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Null Refference - Restarting.
        /// </summary>
        internal static string null_reference {
            get {
                return ResourceManager.GetString("null_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Now opening www.google.com/device and copying the 8 digit code to your clipboard.
        /// </summary>
        internal static string opening_Google {
            get {
                return ResourceManager.GetString("opening_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ArgumentOutOfRangeException - Restarting.
        /// </summary>
        internal static string out_of_range {
            get {
                return ResourceManager.GetString("out_of_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password: {0}.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pokecoins: {0}.
        /// </summary>
        internal static string pokecoin {
            get {
                return ResourceManager.GetString("pokecoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We caught a {0} with {1} CP and {2}% IV&quot;.
        /// </summary>
        internal static string pokemon_caught {
            get {
                return ResourceManager.GetString("pokemon_caught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} with {1} CP and {2}% IV got away....
        /// </summary>
        internal static string pokemon_got_away {
            get {
                return ResourceManager.GetString("pokemon_got_away", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PokeStop: .
        /// </summary>
        internal static string pokestop {
            get {
                return ResourceManager.GetString("pokestop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stardust: {0}.
        /// </summary>
        internal static string stardust {
            get {
                return ResourceManager.GetString("stardust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Task Canceled Exception - Restarting.
        /// </summary>
        internal static string task_canceled {
            get {
                return ResourceManager.GetString("task_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Team: {0}.
        /// </summary>
        internal static string team {
            get {
                return ResourceManager.GetString("team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transfering pokemon disabled.
        /// </summary>
        internal static string transfering_disabled {
            get {
                return ResourceManager.GetString("transfering_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à System URI Format Exception - Restarting.
        /// </summary>
        internal static string uri_exception {
            get {
                return ResourceManager.GetString("uri_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visiting {0} PokeStops.
        /// </summary>
        internal static string visiting_pokestops {
            get {
                return ResourceManager.GetString("visiting_pokestops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à , XP: {0}.
        /// </summary>
        internal static string xp {
            get {
                return ResourceManager.GetString("xp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your version is .
        /// </summary>
        internal static string your_version {
            get {
                return ResourceManager.GetString("your_version", resourceCulture);
            }
        }
    }
}
