// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Data/Avatar/AvatarItem.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Data.Avatar {

  /// <summary>Holder for reflection information generated from POGOProtos/Data/Avatar/AvatarItem.proto</summary>
  public static partial class AvatarItemReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Data/Avatar/AvatarItem.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AvatarItemReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CidQT0dPUHJvdG9zL0RhdGEvQXZhdGFyL0F2YXRhckl0ZW0ucHJvdG8SFlBP",
            "R09Qcm90b3MuRGF0YS5BdmF0YXIiUgoKQXZhdGFySXRlbRIaChJhdmF0YXJf",
            "dGVtcGxhdGVfaWQYASABKAkSGAoQbmV3X3RpbWVzdGFtcF9tcxgCIAEoAxIO",
            "CgZ2aWV3ZWQYAyABKAhiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Data.Avatar.AvatarItem), global::POGOProtos.Data.Avatar.AvatarItem.Parser, new[]{ "AvatarTemplateId", "NewTimestampMs", "Viewed" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AvatarItem : pb::IMessage<AvatarItem> {
    private static readonly pb::MessageParser<AvatarItem> _parser = new pb::MessageParser<AvatarItem>(() => new AvatarItem());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AvatarItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Data.Avatar.AvatarItemReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AvatarItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AvatarItem(AvatarItem other) : this() {
      avatarTemplateId_ = other.avatarTemplateId_;
      newTimestampMs_ = other.newTimestampMs_;
      viewed_ = other.viewed_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AvatarItem Clone() {
      return new AvatarItem(this);
    }

    /// <summary>Field number for the "avatar_template_id" field.</summary>
    public const int AvatarTemplateIdFieldNumber = 1;
    private string avatarTemplateId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AvatarTemplateId {
      get { return avatarTemplateId_; }
      set {
        avatarTemplateId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "new_timestamp_ms" field.</summary>
    public const int NewTimestampMsFieldNumber = 2;
    private long newTimestampMs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long NewTimestampMs {
      get { return newTimestampMs_; }
      set {
        newTimestampMs_ = value;
      }
    }

    /// <summary>Field number for the "viewed" field.</summary>
    public const int ViewedFieldNumber = 3;
    private bool viewed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Viewed {
      get { return viewed_; }
      set {
        viewed_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AvatarItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AvatarItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AvatarTemplateId != other.AvatarTemplateId) return false;
      if (NewTimestampMs != other.NewTimestampMs) return false;
      if (Viewed != other.Viewed) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AvatarTemplateId.Length != 0) hash ^= AvatarTemplateId.GetHashCode();
      if (NewTimestampMs != 0L) hash ^= NewTimestampMs.GetHashCode();
      if (Viewed != false) hash ^= Viewed.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AvatarTemplateId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AvatarTemplateId);
      }
      if (NewTimestampMs != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(NewTimestampMs);
      }
      if (Viewed != false) {
        output.WriteRawTag(24);
        output.WriteBool(Viewed);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AvatarTemplateId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AvatarTemplateId);
      }
      if (NewTimestampMs != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(NewTimestampMs);
      }
      if (Viewed != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AvatarItem other) {
      if (other == null) {
        return;
      }
      if (other.AvatarTemplateId.Length != 0) {
        AvatarTemplateId = other.AvatarTemplateId;
      }
      if (other.NewTimestampMs != 0L) {
        NewTimestampMs = other.NewTimestampMs;
      }
      if (other.Viewed != false) {
        Viewed = other.Viewed;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            AvatarTemplateId = input.ReadString();
            break;
          }
          case 16: {
            NewTimestampMs = input.ReadInt64();
            break;
          }
          case 24: {
            Viewed = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
