// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Enums/Costume.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Enums {

  /// <summary>Holder for reflection information generated from POGOProtos/Enums/Costume.proto</summary>
  public static partial class CostumeReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Enums/Costume.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CostumeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5QT0dPUHJvdG9zL0VudW1zL0Nvc3R1bWUucHJvdG8SEFBPR09Qcm90b3Mu",
            "RW51bXMqLgoHQ29zdHVtZRIRCg1DT1NUVU1FX1VOU0VUEAASEAoMSE9MSURB",
            "WV8yMDE2EAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Enums.Costume), }, null));
    }
    #endregion

  }
  #region Enums
  public enum Costume {
    [pbr::OriginalName("COSTUME_UNSET")] Unset = 0,
    [pbr::OriginalName("HOLIDAY_2016")] Holiday2016 = 1,
  }

  #endregion

}

#endregion Designer generated code
