// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Enums/Form.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Enums {

  /// <summary>Holder for reflection information generated from POGOProtos/Enums/Form.proto</summary>
  public static partial class FormReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Enums/Form.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FormReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtQT0dPUHJvdG9zL0VudW1zL0Zvcm0ucHJvdG8SEFBPR09Qcm90b3MuRW51",
            "bXMqngMKBEZvcm0SDgoKRk9STV9VTlNFVBAAEgsKB1VOT1dOX0EQARILCgdV",
            "Tk9XTl9CEAISCwoHVU5PV05fQxADEgsKB1VOT1dOX0QQBBILCgdVTk9XTl9F",
            "EAUSCwoHVU5PV05fRhAGEgsKB1VOT1dOX0cQBxILCgdVTk9XTl9IEAgSCwoH",
            "VU5PV05fSRAJEgsKB1VOT1dOX0oQChILCgdVTk9XTl9LEAsSCwoHVU5PV05f",
            "TBAMEgsKB1VOT1dOX00QDRILCgdVTk9XTl9OEA4SCwoHVU5PV05fTxAPEgsK",
            "B1VOT1dOX1AQEBILCgdVTk9XTl9REBESCwoHVU5PV05fUhASEgsKB1VOT1dO",
            "X1MQExILCgdVTk9XTl9UEBQSCwoHVU5PV05fVRAVEgsKB1VOT1dOX1YQFhIL",
            "CgdVTk9XTl9XEBcSCwoHVU5PV05fWBAYEgsKB1VOT1dOX1kQGRILCgdVTk9X",
            "Tl9aEBoSFwoTVU5PV05fUVVFU1RJT05fTUFSSxAbEhsKF1VOT1dOX0VYQ0xB",
            "TUFUSU9OX1BPSU5UEBxiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Enums.Form), }, null));
    }
    #endregion

  }
  #region Enums
  public enum Form {
    [pbr::OriginalName("FORM_UNSET")] Unset = 0,
    [pbr::OriginalName("UNOWN_A")] UnownA = 1,
    [pbr::OriginalName("UNOWN_B")] UnownB = 2,
    [pbr::OriginalName("UNOWN_C")] UnownC = 3,
    [pbr::OriginalName("UNOWN_D")] UnownD = 4,
    [pbr::OriginalName("UNOWN_E")] UnownE = 5,
    [pbr::OriginalName("UNOWN_F")] UnownF = 6,
    [pbr::OriginalName("UNOWN_G")] UnownG = 7,
    [pbr::OriginalName("UNOWN_H")] UnownH = 8,
    [pbr::OriginalName("UNOWN_I")] UnownI = 9,
    [pbr::OriginalName("UNOWN_J")] UnownJ = 10,
    [pbr::OriginalName("UNOWN_K")] UnownK = 11,
    [pbr::OriginalName("UNOWN_L")] UnownL = 12,
    [pbr::OriginalName("UNOWN_M")] UnownM = 13,
    [pbr::OriginalName("UNOWN_N")] UnownN = 14,
    [pbr::OriginalName("UNOWN_O")] UnownO = 15,
    [pbr::OriginalName("UNOWN_P")] UnownP = 16,
    [pbr::OriginalName("UNOWN_Q")] UnownQ = 17,
    [pbr::OriginalName("UNOWN_R")] UnownR = 18,
    [pbr::OriginalName("UNOWN_S")] UnownS = 19,
    [pbr::OriginalName("UNOWN_T")] UnownT = 20,
    [pbr::OriginalName("UNOWN_U")] UnownU = 21,
    [pbr::OriginalName("UNOWN_V")] UnownV = 22,
    [pbr::OriginalName("UNOWN_W")] UnownW = 23,
    [pbr::OriginalName("UNOWN_X")] UnownX = 24,
    [pbr::OriginalName("UNOWN_Y")] UnownY = 25,
    [pbr::OriginalName("UNOWN_Z")] UnownZ = 26,
    [pbr::OriginalName("UNOWN_QUESTION_MARK")] UnownQuestionMark = 27,
    [pbr::OriginalName("UNOWN_EXCLAMATION_POINT")] UnownExclamationPoint = 28,
  }

  #endregion

}

#endregion Designer generated code
