// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Map/Fort/FortSponsor.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Map.Fort {

  /// <summary>Holder for reflection information generated from POGOProtos/Map/Fort/FortSponsor.proto</summary>
  public static partial class FortSponsorReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Map/Fort/FortSponsor.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FortSponsorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVQT0dPUHJvdG9zL01hcC9Gb3J0L0ZvcnRTcG9uc29yLnByb3RvEhNQT0dP",
            "UHJvdG9zLk1hcC5Gb3J0KsIBCgtGb3J0U3BvbnNvchIRCg1VTlNFVF9TUE9O",
            "U09SEAASDQoJTUNET05BTERTEAESEQoNUE9LRU1PTl9TVE9SRRACEggKBFRP",
            "SE8QAxIMCghTT0ZUQkFOSxAEEgkKBUdMT0JFEAUSCwoHU1BBVFVMQRAGEg8K",
            "C1RIRVJNT01FVEVSEAcSCQoFS05JRkUQCBIJCgVHUklMTBAJEgoKBlNNT0tF",
            "UhAKEgcKA1BBThALEgcKA0JCURAMEgkKBUZSWUVSEA1iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Map.Fort.FortSponsor), }, null));
    }
    #endregion

  }
  #region Enums
  public enum FortSponsor {
    [pbr::OriginalName("UNSET_SPONSOR")] UnsetSponsor = 0,
    [pbr::OriginalName("MCDONALDS")] Mcdonalds = 1,
    [pbr::OriginalName("POKEMON_STORE")] PokemonStore = 2,
    [pbr::OriginalName("TOHO")] Toho = 3,
    [pbr::OriginalName("SOFTBANK")] Softbank = 4,
    [pbr::OriginalName("GLOBE")] Globe = 5,
    [pbr::OriginalName("SPATULA")] Spatula = 6,
    [pbr::OriginalName("THERMOMETER")] Thermometer = 7,
    [pbr::OriginalName("KNIFE")] Knife = 8,
    [pbr::OriginalName("GRILL")] Grill = 9,
    [pbr::OriginalName("SMOKER")] Smoker = 10,
    [pbr::OriginalName("PAN")] Pan = 11,
    [pbr::OriginalName("BBQ")] Bbq = 12,
    [pbr::OriginalName("FRYER")] Fryer = 13,
  }

  #endregion

}

#endregion Designer generated code
