// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Settings/Master/Pokemon/EvolutionBranch.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Settings.Master.Pokemon {

  /// <summary>Holder for reflection information generated from POGOProtos/Settings/Master/Pokemon/EvolutionBranch.proto</summary>
  public static partial class EvolutionBranchReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Settings/Master/Pokemon/EvolutionBranch.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EvolutionBranchReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjhQT0dPUHJvdG9zL1NldHRpbmdzL01hc3Rlci9Qb2tlbW9uL0V2b2x1dGlv",
            "bkJyYW5jaC5wcm90bxIiUE9HT1Byb3Rvcy5TZXR0aW5ncy5NYXN0ZXIuUG9r",
            "ZW1vbhogUE9HT1Byb3Rvcy9FbnVtcy9Qb2tlbW9uSWQucHJvdG8aJlBPR09Q",
            "cm90b3MvSW52ZW50b3J5L0l0ZW0vSXRlbUlkLnByb3RvIogBCg9Fdm9sdXRp",
            "b25CcmFuY2gSLgoJZXZvbHV0aW9uGAEgASgOMhsuUE9HT1Byb3Rvcy5FbnVt",
            "cy5Qb2tlbW9uSWQSRQoaZXZvbHV0aW9uX2l0ZW1fcmVxdWlyZW1lbnQYAiAB",
            "KA4yIS5QT0dPUHJvdG9zLkludmVudG9yeS5JdGVtLkl0ZW1JZGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Enums.PokemonIdReflection.Descriptor, global::POGOProtos.Inventory.Item.ItemIdReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Settings.Master.Pokemon.EvolutionBranch), global::POGOProtos.Settings.Master.Pokemon.EvolutionBranch.Parser, new[]{ "Evolution", "EvolutionItemRequirement" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EvolutionBranch : pb::IMessage<EvolutionBranch> {
    private static readonly pb::MessageParser<EvolutionBranch> _parser = new pb::MessageParser<EvolutionBranch>(() => new EvolutionBranch());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EvolutionBranch> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Settings.Master.Pokemon.EvolutionBranchReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EvolutionBranch() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EvolutionBranch(EvolutionBranch other) : this() {
      evolution_ = other.evolution_;
      evolutionItemRequirement_ = other.evolutionItemRequirement_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EvolutionBranch Clone() {
      return new EvolutionBranch(this);
    }

    /// <summary>Field number for the "evolution" field.</summary>
    public const int EvolutionFieldNumber = 1;
    private global::POGOProtos.Enums.PokemonId evolution_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Enums.PokemonId Evolution {
      get { return evolution_; }
      set {
        evolution_ = value;
      }
    }

    /// <summary>Field number for the "evolution_item_requirement" field.</summary>
    public const int EvolutionItemRequirementFieldNumber = 2;
    private global::POGOProtos.Inventory.Item.ItemId evolutionItemRequirement_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Inventory.Item.ItemId EvolutionItemRequirement {
      get { return evolutionItemRequirement_; }
      set {
        evolutionItemRequirement_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EvolutionBranch);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EvolutionBranch other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Evolution != other.Evolution) return false;
      if (EvolutionItemRequirement != other.EvolutionItemRequirement) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Evolution != 0) hash ^= Evolution.GetHashCode();
      if (EvolutionItemRequirement != 0) hash ^= EvolutionItemRequirement.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Evolution != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Evolution);
      }
      if (EvolutionItemRequirement != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) EvolutionItemRequirement);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Evolution != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Evolution);
      }
      if (EvolutionItemRequirement != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EvolutionItemRequirement);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EvolutionBranch other) {
      if (other == null) {
        return;
      }
      if (other.Evolution != 0) {
        Evolution = other.Evolution;
      }
      if (other.EvolutionItemRequirement != 0) {
        EvolutionItemRequirement = other.EvolutionItemRequirement;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            evolution_ = (global::POGOProtos.Enums.PokemonId) input.ReadEnum();
            break;
          }
          case 16: {
            evolutionItemRequirement_ = (global::POGOProtos.Inventory.Item.ItemId) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
