// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Settings/GlobalSettings.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Settings {

  /// <summary>Holder for reflection information generated from POGOProtos/Settings/GlobalSettings.proto</summary>
  public static partial class GlobalSettingsReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Settings/GlobalSettings.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GlobalSettingsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CihQT0dPUHJvdG9zL1NldHRpbmdzL0dsb2JhbFNldHRpbmdzLnByb3RvEhNQ",
            "T0dPUHJvdG9zLlNldHRpbmdzGidQT0dPUHJvdG9zL1NldHRpbmdzL0V2ZW50",
            "U2V0dGluZ3MucHJvdG8aKlBPR09Qcm90b3MvU2V0dGluZ3MvRmVzdGl2YWxT",
            "ZXR0aW5ncy5wcm90bxomUE9HT1Byb3Rvcy9TZXR0aW5ncy9Gb3J0U2V0dGlu",
            "Z3MucHJvdG8aJVBPR09Qcm90b3MvU2V0dGluZ3MvR3BzU2V0dGluZ3MucHJv",
            "dG8aK1BPR09Qcm90b3MvU2V0dGluZ3MvSW52ZW50b3J5U2V0dGluZ3MucHJv",
            "dG8aJ1BPR09Qcm90b3MvU2V0dGluZ3MvTGV2ZWxTZXR0aW5ncy5wcm90bxol",
            "UE9HT1Byb3Rvcy9TZXR0aW5ncy9NYXBTZXR0aW5ncy5wcm90bxomUE9HT1By",
            "b3Rvcy9TZXR0aW5ncy9OZXdzU2V0dGluZ3MucHJvdG8aJ1BPR09Qcm90b3Mv",
            "U2V0dGluZ3MvU2ZpZGFTZXR0aW5ncy5wcm90byLpBAoOR2xvYmFsU2V0dGlu",
            "Z3MSOAoNZm9ydF9zZXR0aW5ncxgCIAEoCzIhLlBPR09Qcm90b3MuU2V0dGlu",
            "Z3MuRm9ydFNldHRpbmdzEjYKDG1hcF9zZXR0aW5ncxgDIAEoCzIgLlBPR09Q",
            "cm90b3MuU2V0dGluZ3MuTWFwU2V0dGluZ3MSOgoObGV2ZWxfc2V0dGluZ3MY",
            "BCABKAsyIi5QT0dPUHJvdG9zLlNldHRpbmdzLkxldmVsU2V0dGluZ3MSQgoS",
            "aW52ZW50b3J5X3NldHRpbmdzGAUgASgLMiYuUE9HT1Byb3Rvcy5TZXR0aW5n",
            "cy5JbnZlbnRvcnlTZXR0aW5ncxIeChZtaW5pbXVtX2NsaWVudF92ZXJzaW9u",
            "GAYgASgJEjYKDGdwc19zZXR0aW5ncxgHIAEoCzIgLlBPR09Qcm90b3MuU2V0",
            "dGluZ3MuR3BzU2V0dGluZ3MSQAoRZmVzdGl2YWxfc2V0dGluZ3MYCCABKAsy",
            "JS5QT0dPUHJvdG9zLlNldHRpbmdzLkZlc3RpdmFsU2V0dGluZ3MSOgoOZXZl",
            "bnRfc2V0dGluZ3MYCSABKAsyIi5QT0dPUHJvdG9zLlNldHRpbmdzLkV2ZW50",
            "U2V0dGluZ3MSGQoRbWF4X3Bva2Vtb25fdHlwZXMYCiABKAUSOgoOc2ZpZGFf",
            "c2V0dGluZ3MYCyABKAsyIi5QT0dPUHJvdG9zLlNldHRpbmdzLlNmaWRhU2V0",
            "dGluZ3MSOAoNbmV3c19zZXR0aW5ncxgMIAEoCzIhLlBPR09Qcm90b3MuU2V0",
            "dGluZ3MuTmV3c1NldHRpbmdzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Settings.EventSettingsReflection.Descriptor, global::POGOProtos.Settings.FestivalSettingsReflection.Descriptor, global::POGOProtos.Settings.FortSettingsReflection.Descriptor, global::POGOProtos.Settings.GpsSettingsReflection.Descriptor, global::POGOProtos.Settings.InventorySettingsReflection.Descriptor, global::POGOProtos.Settings.LevelSettingsReflection.Descriptor, global::POGOProtos.Settings.MapSettingsReflection.Descriptor, global::POGOProtos.Settings.NewsSettingsReflection.Descriptor, global::POGOProtos.Settings.SfidaSettingsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Settings.GlobalSettings), global::POGOProtos.Settings.GlobalSettings.Parser, new[]{ "FortSettings", "MapSettings", "LevelSettings", "InventorySettings", "MinimumClientVersion", "GpsSettings", "FestivalSettings", "EventSettings", "MaxPokemonTypes", "SfidaSettings", "NewsSettings" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GlobalSettings : pb::IMessage<GlobalSettings> {
    private static readonly pb::MessageParser<GlobalSettings> _parser = new pb::MessageParser<GlobalSettings>(() => new GlobalSettings());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GlobalSettings> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Settings.GlobalSettingsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GlobalSettings() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GlobalSettings(GlobalSettings other) : this() {
      FortSettings = other.fortSettings_ != null ? other.FortSettings.Clone() : null;
      MapSettings = other.mapSettings_ != null ? other.MapSettings.Clone() : null;
      LevelSettings = other.levelSettings_ != null ? other.LevelSettings.Clone() : null;
      InventorySettings = other.inventorySettings_ != null ? other.InventorySettings.Clone() : null;
      minimumClientVersion_ = other.minimumClientVersion_;
      GpsSettings = other.gpsSettings_ != null ? other.GpsSettings.Clone() : null;
      FestivalSettings = other.festivalSettings_ != null ? other.FestivalSettings.Clone() : null;
      EventSettings = other.eventSettings_ != null ? other.EventSettings.Clone() : null;
      maxPokemonTypes_ = other.maxPokemonTypes_;
      SfidaSettings = other.sfidaSettings_ != null ? other.SfidaSettings.Clone() : null;
      NewsSettings = other.newsSettings_ != null ? other.NewsSettings.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GlobalSettings Clone() {
      return new GlobalSettings(this);
    }

    /// <summary>Field number for the "fort_settings" field.</summary>
    public const int FortSettingsFieldNumber = 2;
    private global::POGOProtos.Settings.FortSettings fortSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.FortSettings FortSettings {
      get { return fortSettings_; }
      set {
        fortSettings_ = value;
      }
    }

    /// <summary>Field number for the "map_settings" field.</summary>
    public const int MapSettingsFieldNumber = 3;
    private global::POGOProtos.Settings.MapSettings mapSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.MapSettings MapSettings {
      get { return mapSettings_; }
      set {
        mapSettings_ = value;
      }
    }

    /// <summary>Field number for the "level_settings" field.</summary>
    public const int LevelSettingsFieldNumber = 4;
    private global::POGOProtos.Settings.LevelSettings levelSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.LevelSettings LevelSettings {
      get { return levelSettings_; }
      set {
        levelSettings_ = value;
      }
    }

    /// <summary>Field number for the "inventory_settings" field.</summary>
    public const int InventorySettingsFieldNumber = 5;
    private global::POGOProtos.Settings.InventorySettings inventorySettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.InventorySettings InventorySettings {
      get { return inventorySettings_; }
      set {
        inventorySettings_ = value;
      }
    }

    /// <summary>Field number for the "minimum_client_version" field.</summary>
    public const int MinimumClientVersionFieldNumber = 6;
    private string minimumClientVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MinimumClientVersion {
      get { return minimumClientVersion_; }
      set {
        minimumClientVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gps_settings" field.</summary>
    public const int GpsSettingsFieldNumber = 7;
    private global::POGOProtos.Settings.GpsSettings gpsSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.GpsSettings GpsSettings {
      get { return gpsSettings_; }
      set {
        gpsSettings_ = value;
      }
    }

    /// <summary>Field number for the "festival_settings" field.</summary>
    public const int FestivalSettingsFieldNumber = 8;
    private global::POGOProtos.Settings.FestivalSettings festivalSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.FestivalSettings FestivalSettings {
      get { return festivalSettings_; }
      set {
        festivalSettings_ = value;
      }
    }

    /// <summary>Field number for the "event_settings" field.</summary>
    public const int EventSettingsFieldNumber = 9;
    private global::POGOProtos.Settings.EventSettings eventSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.EventSettings EventSettings {
      get { return eventSettings_; }
      set {
        eventSettings_ = value;
      }
    }

    /// <summary>Field number for the "max_pokemon_types" field.</summary>
    public const int MaxPokemonTypesFieldNumber = 10;
    private int maxPokemonTypes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MaxPokemonTypes {
      get { return maxPokemonTypes_; }
      set {
        maxPokemonTypes_ = value;
      }
    }

    /// <summary>Field number for the "sfida_settings" field.</summary>
    public const int SfidaSettingsFieldNumber = 11;
    private global::POGOProtos.Settings.SfidaSettings sfidaSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.SfidaSettings SfidaSettings {
      get { return sfidaSettings_; }
      set {
        sfidaSettings_ = value;
      }
    }

    /// <summary>Field number for the "news_settings" field.</summary>
    public const int NewsSettingsFieldNumber = 12;
    private global::POGOProtos.Settings.NewsSettings newsSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.NewsSettings NewsSettings {
      get { return newsSettings_; }
      set {
        newsSettings_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GlobalSettings);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GlobalSettings other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(FortSettings, other.FortSettings)) return false;
      if (!object.Equals(MapSettings, other.MapSettings)) return false;
      if (!object.Equals(LevelSettings, other.LevelSettings)) return false;
      if (!object.Equals(InventorySettings, other.InventorySettings)) return false;
      if (MinimumClientVersion != other.MinimumClientVersion) return false;
      if (!object.Equals(GpsSettings, other.GpsSettings)) return false;
      if (!object.Equals(FestivalSettings, other.FestivalSettings)) return false;
      if (!object.Equals(EventSettings, other.EventSettings)) return false;
      if (MaxPokemonTypes != other.MaxPokemonTypes) return false;
      if (!object.Equals(SfidaSettings, other.SfidaSettings)) return false;
      if (!object.Equals(NewsSettings, other.NewsSettings)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (fortSettings_ != null) hash ^= FortSettings.GetHashCode();
      if (mapSettings_ != null) hash ^= MapSettings.GetHashCode();
      if (levelSettings_ != null) hash ^= LevelSettings.GetHashCode();
      if (inventorySettings_ != null) hash ^= InventorySettings.GetHashCode();
      if (MinimumClientVersion.Length != 0) hash ^= MinimumClientVersion.GetHashCode();
      if (gpsSettings_ != null) hash ^= GpsSettings.GetHashCode();
      if (festivalSettings_ != null) hash ^= FestivalSettings.GetHashCode();
      if (eventSettings_ != null) hash ^= EventSettings.GetHashCode();
      if (MaxPokemonTypes != 0) hash ^= MaxPokemonTypes.GetHashCode();
      if (sfidaSettings_ != null) hash ^= SfidaSettings.GetHashCode();
      if (newsSettings_ != null) hash ^= NewsSettings.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (fortSettings_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(FortSettings);
      }
      if (mapSettings_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(MapSettings);
      }
      if (levelSettings_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LevelSettings);
      }
      if (inventorySettings_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(InventorySettings);
      }
      if (MinimumClientVersion.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(MinimumClientVersion);
      }
      if (gpsSettings_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(GpsSettings);
      }
      if (festivalSettings_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(FestivalSettings);
      }
      if (eventSettings_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(EventSettings);
      }
      if (MaxPokemonTypes != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(MaxPokemonTypes);
      }
      if (sfidaSettings_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(SfidaSettings);
      }
      if (newsSettings_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(NewsSettings);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (fortSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FortSettings);
      }
      if (mapSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MapSettings);
      }
      if (levelSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LevelSettings);
      }
      if (inventorySettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InventorySettings);
      }
      if (MinimumClientVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MinimumClientVersion);
      }
      if (gpsSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GpsSettings);
      }
      if (festivalSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FestivalSettings);
      }
      if (eventSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EventSettings);
      }
      if (MaxPokemonTypes != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxPokemonTypes);
      }
      if (sfidaSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SfidaSettings);
      }
      if (newsSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NewsSettings);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GlobalSettings other) {
      if (other == null) {
        return;
      }
      if (other.fortSettings_ != null) {
        if (fortSettings_ == null) {
          fortSettings_ = new global::POGOProtos.Settings.FortSettings();
        }
        FortSettings.MergeFrom(other.FortSettings);
      }
      if (other.mapSettings_ != null) {
        if (mapSettings_ == null) {
          mapSettings_ = new global::POGOProtos.Settings.MapSettings();
        }
        MapSettings.MergeFrom(other.MapSettings);
      }
      if (other.levelSettings_ != null) {
        if (levelSettings_ == null) {
          levelSettings_ = new global::POGOProtos.Settings.LevelSettings();
        }
        LevelSettings.MergeFrom(other.LevelSettings);
      }
      if (other.inventorySettings_ != null) {
        if (inventorySettings_ == null) {
          inventorySettings_ = new global::POGOProtos.Settings.InventorySettings();
        }
        InventorySettings.MergeFrom(other.InventorySettings);
      }
      if (other.MinimumClientVersion.Length != 0) {
        MinimumClientVersion = other.MinimumClientVersion;
      }
      if (other.gpsSettings_ != null) {
        if (gpsSettings_ == null) {
          gpsSettings_ = new global::POGOProtos.Settings.GpsSettings();
        }
        GpsSettings.MergeFrom(other.GpsSettings);
      }
      if (other.festivalSettings_ != null) {
        if (festivalSettings_ == null) {
          festivalSettings_ = new global::POGOProtos.Settings.FestivalSettings();
        }
        FestivalSettings.MergeFrom(other.FestivalSettings);
      }
      if (other.eventSettings_ != null) {
        if (eventSettings_ == null) {
          eventSettings_ = new global::POGOProtos.Settings.EventSettings();
        }
        EventSettings.MergeFrom(other.EventSettings);
      }
      if (other.MaxPokemonTypes != 0) {
        MaxPokemonTypes = other.MaxPokemonTypes;
      }
      if (other.sfidaSettings_ != null) {
        if (sfidaSettings_ == null) {
          sfidaSettings_ = new global::POGOProtos.Settings.SfidaSettings();
        }
        SfidaSettings.MergeFrom(other.SfidaSettings);
      }
      if (other.newsSettings_ != null) {
        if (newsSettings_ == null) {
          newsSettings_ = new global::POGOProtos.Settings.NewsSettings();
        }
        NewsSettings.MergeFrom(other.NewsSettings);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 18: {
            if (fortSettings_ == null) {
              fortSettings_ = new global::POGOProtos.Settings.FortSettings();
            }
            input.ReadMessage(fortSettings_);
            break;
          }
          case 26: {
            if (mapSettings_ == null) {
              mapSettings_ = new global::POGOProtos.Settings.MapSettings();
            }
            input.ReadMessage(mapSettings_);
            break;
          }
          case 34: {
            if (levelSettings_ == null) {
              levelSettings_ = new global::POGOProtos.Settings.LevelSettings();
            }
            input.ReadMessage(levelSettings_);
            break;
          }
          case 42: {
            if (inventorySettings_ == null) {
              inventorySettings_ = new global::POGOProtos.Settings.InventorySettings();
            }
            input.ReadMessage(inventorySettings_);
            break;
          }
          case 50: {
            MinimumClientVersion = input.ReadString();
            break;
          }
          case 58: {
            if (gpsSettings_ == null) {
              gpsSettings_ = new global::POGOProtos.Settings.GpsSettings();
            }
            input.ReadMessage(gpsSettings_);
            break;
          }
          case 66: {
            if (festivalSettings_ == null) {
              festivalSettings_ = new global::POGOProtos.Settings.FestivalSettings();
            }
            input.ReadMessage(festivalSettings_);
            break;
          }
          case 74: {
            if (eventSettings_ == null) {
              eventSettings_ = new global::POGOProtos.Settings.EventSettings();
            }
            input.ReadMessage(eventSettings_);
            break;
          }
          case 80: {
            MaxPokemonTypes = input.ReadInt32();
            break;
          }
          case 90: {
            if (sfidaSettings_ == null) {
              sfidaSettings_ = new global::POGOProtos.Settings.SfidaSettings();
            }
            input.ReadMessage(sfidaSettings_);
            break;
          }
          case 98: {
            if (newsSettings_ == null) {
              newsSettings_ = new global::POGOProtos.Settings.NewsSettings();
            }
            input.ReadMessage(newsSettings_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
