// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Data/Player/PlayerAvatar.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Data.Player {

  /// <summary>Holder for reflection information generated from POGOProtos/Data/Player/PlayerAvatar.proto</summary>
  public static partial class PlayerAvatarReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Data/Player/PlayerAvatar.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerAvatarReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CilQT0dPUHJvdG9zL0RhdGEvUGxheWVyL1BsYXllckF2YXRhci5wcm90bxIW",
            "UE9HT1Byb3Rvcy5EYXRhLlBsYXllciKgAwoMUGxheWVyQXZhdGFyEgwKBHNr",
            "aW4YAiABKAUSDAoEaGFpchgDIAEoBRINCgVzaGlydBgEIAEoBRINCgVwYW50",
            "cxgFIAEoBRILCgNoYXQYBiABKAUSDQoFc2hvZXMYByABKAUSDgoGYXZhdGFy",
            "GAggASgFEgwKBGV5ZXMYCSABKAUSEAoIYmFja3BhY2sYCiABKAUSEwoLYXZh",
            "dGFyX2hhaXIYCyABKAkSFAoMYXZhdGFyX3NoaXJ0GAwgASgJEhQKDGF2YXRh",
            "cl9wYW50cxgNIAEoCRISCgphdmF0YXJfaGF0GA4gASgJEhQKDGF2YXRhcl9z",
            "aG9lcxgPIAEoCRITCgthdmF0YXJfZXllcxgQIAEoCRIXCg9hdmF0YXJfYmFj",
            "a3BhY2sYESABKAkSFQoNYXZhdGFyX2dsb3ZlcxgSIAEoCRIUCgxhdmF0YXJf",
            "c29ja3MYEyABKAkSEwoLYXZhdGFyX2JlbHQYFCABKAkSFgoOYXZhdGFyX2ds",
            "YXNzZXMYFSABKAkSFwoPYXZhdGFyX25lY2tsYWNlGBYgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Data.Player.PlayerAvatar), global::POGOProtos.Data.Player.PlayerAvatar.Parser, new[]{ "Skin", "Hair", "Shirt", "Pants", "Hat", "Shoes", "Avatar", "Eyes", "Backpack", "AvatarHair", "AvatarShirt", "AvatarPants", "AvatarHat", "AvatarShoes", "AvatarEyes", "AvatarBackpack", "AvatarGloves", "AvatarSocks", "AvatarBelt", "AvatarGlasses", "AvatarNecklace" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PlayerAvatar : pb::IMessage<PlayerAvatar> {
    private static readonly pb::MessageParser<PlayerAvatar> _parser = new pb::MessageParser<PlayerAvatar>(() => new PlayerAvatar());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayerAvatar> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Data.Player.PlayerAvatarReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerAvatar() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerAvatar(PlayerAvatar other) : this() {
      skin_ = other.skin_;
      hair_ = other.hair_;
      shirt_ = other.shirt_;
      pants_ = other.pants_;
      hat_ = other.hat_;
      shoes_ = other.shoes_;
      avatar_ = other.avatar_;
      eyes_ = other.eyes_;
      backpack_ = other.backpack_;
      avatarHair_ = other.avatarHair_;
      avatarShirt_ = other.avatarShirt_;
      avatarPants_ = other.avatarPants_;
      avatarHat_ = other.avatarHat_;
      avatarShoes_ = other.avatarShoes_;
      avatarEyes_ = other.avatarEyes_;
      avatarBackpack_ = other.avatarBackpack_;
      avatarGloves_ = other.avatarGloves_;
      avatarSocks_ = other.avatarSocks_;
      avatarBelt_ = other.avatarBelt_;
      avatarGlasses_ = other.avatarGlasses_;
      avatarNecklace_ = other.avatarNecklace_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerAvatar Clone() {
      return new PlayerAvatar(this);
    }

    /// <summary>Field number for the "skin" field.</summary>
    public const int SkinFieldNumber = 2;
    private int skin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Skin {
      get { return skin_; }
      set {
        skin_ = value;
      }
    }

    /// <summary>Field number for the "hair" field.</summary>
    public const int HairFieldNumber = 3;
    private int hair_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Hair {
      get { return hair_; }
      set {
        hair_ = value;
      }
    }

    /// <summary>Field number for the "shirt" field.</summary>
    public const int ShirtFieldNumber = 4;
    private int shirt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Shirt {
      get { return shirt_; }
      set {
        shirt_ = value;
      }
    }

    /// <summary>Field number for the "pants" field.</summary>
    public const int PantsFieldNumber = 5;
    private int pants_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Pants {
      get { return pants_; }
      set {
        pants_ = value;
      }
    }

    /// <summary>Field number for the "hat" field.</summary>
    public const int HatFieldNumber = 6;
    private int hat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Hat {
      get { return hat_; }
      set {
        hat_ = value;
      }
    }

    /// <summary>Field number for the "shoes" field.</summary>
    public const int ShoesFieldNumber = 7;
    private int shoes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Shoes {
      get { return shoes_; }
      set {
        shoes_ = value;
      }
    }

    /// <summary>Field number for the "avatar" field.</summary>
    public const int AvatarFieldNumber = 8;
    private int avatar_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Avatar {
      get { return avatar_; }
      set {
        avatar_ = value;
      }
    }

    /// <summary>Field number for the "eyes" field.</summary>
    public const int EyesFieldNumber = 9;
    private int eyes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Eyes {
      get { return eyes_; }
      set {
        eyes_ = value;
      }
    }

    /// <summary>Field number for the "backpack" field.</summary>
    public const int BackpackFieldNumber = 10;
    private int backpack_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Backpack {
      get { return backpack_; }
      set {
        backpack_ = value;
      }
    }

    /// <summary>Field number for the "avatar_hair" field.</summary>
    public const int AvatarHairFieldNumber = 11;
    private string avatarHair_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AvatarHair {
      get { return avatarHair_; }
      set {
        avatarHair_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "avatar_shirt" field.</summary>
    public const int AvatarShirtFieldNumber = 12;
    private string avatarShirt_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AvatarShirt {
      get { return avatarShirt_; }
      set {
        avatarShirt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "avatar_pants" field.</summary>
    public const int AvatarPantsFieldNumber = 13;
    private string avatarPants_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AvatarPants {
      get { return avatarPants_; }
      set {
        avatarPants_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "avatar_hat" field.</summary>
    public const int AvatarHatFieldNumber = 14;
    private string avatarHat_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AvatarHat {
      get { return avatarHat_; }
      set {
        avatarHat_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "avatar_shoes" field.</summary>
    public const int AvatarShoesFieldNumber = 15;
    private string avatarShoes_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AvatarShoes {
      get { return avatarShoes_; }
      set {
        avatarShoes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "avatar_eyes" field.</summary>
    public const int AvatarEyesFieldNumber = 16;
    private string avatarEyes_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AvatarEyes {
      get { return avatarEyes_; }
      set {
        avatarEyes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "avatar_backpack" field.</summary>
    public const int AvatarBackpackFieldNumber = 17;
    private string avatarBackpack_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AvatarBackpack {
      get { return avatarBackpack_; }
      set {
        avatarBackpack_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "avatar_gloves" field.</summary>
    public const int AvatarGlovesFieldNumber = 18;
    private string avatarGloves_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AvatarGloves {
      get { return avatarGloves_; }
      set {
        avatarGloves_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "avatar_socks" field.</summary>
    public const int AvatarSocksFieldNumber = 19;
    private string avatarSocks_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AvatarSocks {
      get { return avatarSocks_; }
      set {
        avatarSocks_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "avatar_belt" field.</summary>
    public const int AvatarBeltFieldNumber = 20;
    private string avatarBelt_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AvatarBelt {
      get { return avatarBelt_; }
      set {
        avatarBelt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "avatar_glasses" field.</summary>
    public const int AvatarGlassesFieldNumber = 21;
    private string avatarGlasses_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AvatarGlasses {
      get { return avatarGlasses_; }
      set {
        avatarGlasses_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "avatar_necklace" field.</summary>
    public const int AvatarNecklaceFieldNumber = 22;
    private string avatarNecklace_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AvatarNecklace {
      get { return avatarNecklace_; }
      set {
        avatarNecklace_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlayerAvatar);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlayerAvatar other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Skin != other.Skin) return false;
      if (Hair != other.Hair) return false;
      if (Shirt != other.Shirt) return false;
      if (Pants != other.Pants) return false;
      if (Hat != other.Hat) return false;
      if (Shoes != other.Shoes) return false;
      if (Avatar != other.Avatar) return false;
      if (Eyes != other.Eyes) return false;
      if (Backpack != other.Backpack) return false;
      if (AvatarHair != other.AvatarHair) return false;
      if (AvatarShirt != other.AvatarShirt) return false;
      if (AvatarPants != other.AvatarPants) return false;
      if (AvatarHat != other.AvatarHat) return false;
      if (AvatarShoes != other.AvatarShoes) return false;
      if (AvatarEyes != other.AvatarEyes) return false;
      if (AvatarBackpack != other.AvatarBackpack) return false;
      if (AvatarGloves != other.AvatarGloves) return false;
      if (AvatarSocks != other.AvatarSocks) return false;
      if (AvatarBelt != other.AvatarBelt) return false;
      if (AvatarGlasses != other.AvatarGlasses) return false;
      if (AvatarNecklace != other.AvatarNecklace) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Skin != 0) hash ^= Skin.GetHashCode();
      if (Hair != 0) hash ^= Hair.GetHashCode();
      if (Shirt != 0) hash ^= Shirt.GetHashCode();
      if (Pants != 0) hash ^= Pants.GetHashCode();
      if (Hat != 0) hash ^= Hat.GetHashCode();
      if (Shoes != 0) hash ^= Shoes.GetHashCode();
      if (Avatar != 0) hash ^= Avatar.GetHashCode();
      if (Eyes != 0) hash ^= Eyes.GetHashCode();
      if (Backpack != 0) hash ^= Backpack.GetHashCode();
      if (AvatarHair.Length != 0) hash ^= AvatarHair.GetHashCode();
      if (AvatarShirt.Length != 0) hash ^= AvatarShirt.GetHashCode();
      if (AvatarPants.Length != 0) hash ^= AvatarPants.GetHashCode();
      if (AvatarHat.Length != 0) hash ^= AvatarHat.GetHashCode();
      if (AvatarShoes.Length != 0) hash ^= AvatarShoes.GetHashCode();
      if (AvatarEyes.Length != 0) hash ^= AvatarEyes.GetHashCode();
      if (AvatarBackpack.Length != 0) hash ^= AvatarBackpack.GetHashCode();
      if (AvatarGloves.Length != 0) hash ^= AvatarGloves.GetHashCode();
      if (AvatarSocks.Length != 0) hash ^= AvatarSocks.GetHashCode();
      if (AvatarBelt.Length != 0) hash ^= AvatarBelt.GetHashCode();
      if (AvatarGlasses.Length != 0) hash ^= AvatarGlasses.GetHashCode();
      if (AvatarNecklace.Length != 0) hash ^= AvatarNecklace.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Skin != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Skin);
      }
      if (Hair != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Hair);
      }
      if (Shirt != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Shirt);
      }
      if (Pants != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Pants);
      }
      if (Hat != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Hat);
      }
      if (Shoes != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Shoes);
      }
      if (Avatar != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Avatar);
      }
      if (Eyes != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Eyes);
      }
      if (Backpack != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(Backpack);
      }
      if (AvatarHair.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(AvatarHair);
      }
      if (AvatarShirt.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(AvatarShirt);
      }
      if (AvatarPants.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(AvatarPants);
      }
      if (AvatarHat.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(AvatarHat);
      }
      if (AvatarShoes.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(AvatarShoes);
      }
      if (AvatarEyes.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(AvatarEyes);
      }
      if (AvatarBackpack.Length != 0) {
        output.WriteRawTag(138, 1);
        output.WriteString(AvatarBackpack);
      }
      if (AvatarGloves.Length != 0) {
        output.WriteRawTag(146, 1);
        output.WriteString(AvatarGloves);
      }
      if (AvatarSocks.Length != 0) {
        output.WriteRawTag(154, 1);
        output.WriteString(AvatarSocks);
      }
      if (AvatarBelt.Length != 0) {
        output.WriteRawTag(162, 1);
        output.WriteString(AvatarBelt);
      }
      if (AvatarGlasses.Length != 0) {
        output.WriteRawTag(170, 1);
        output.WriteString(AvatarGlasses);
      }
      if (AvatarNecklace.Length != 0) {
        output.WriteRawTag(178, 1);
        output.WriteString(AvatarNecklace);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Skin != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Skin);
      }
      if (Hair != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Hair);
      }
      if (Shirt != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Shirt);
      }
      if (Pants != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Pants);
      }
      if (Hat != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Hat);
      }
      if (Shoes != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Shoes);
      }
      if (Avatar != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Avatar);
      }
      if (Eyes != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Eyes);
      }
      if (Backpack != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Backpack);
      }
      if (AvatarHair.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AvatarHair);
      }
      if (AvatarShirt.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AvatarShirt);
      }
      if (AvatarPants.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AvatarPants);
      }
      if (AvatarHat.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AvatarHat);
      }
      if (AvatarShoes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AvatarShoes);
      }
      if (AvatarEyes.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(AvatarEyes);
      }
      if (AvatarBackpack.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(AvatarBackpack);
      }
      if (AvatarGloves.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(AvatarGloves);
      }
      if (AvatarSocks.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(AvatarSocks);
      }
      if (AvatarBelt.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(AvatarBelt);
      }
      if (AvatarGlasses.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(AvatarGlasses);
      }
      if (AvatarNecklace.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(AvatarNecklace);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlayerAvatar other) {
      if (other == null) {
        return;
      }
      if (other.Skin != 0) {
        Skin = other.Skin;
      }
      if (other.Hair != 0) {
        Hair = other.Hair;
      }
      if (other.Shirt != 0) {
        Shirt = other.Shirt;
      }
      if (other.Pants != 0) {
        Pants = other.Pants;
      }
      if (other.Hat != 0) {
        Hat = other.Hat;
      }
      if (other.Shoes != 0) {
        Shoes = other.Shoes;
      }
      if (other.Avatar != 0) {
        Avatar = other.Avatar;
      }
      if (other.Eyes != 0) {
        Eyes = other.Eyes;
      }
      if (other.Backpack != 0) {
        Backpack = other.Backpack;
      }
      if (other.AvatarHair.Length != 0) {
        AvatarHair = other.AvatarHair;
      }
      if (other.AvatarShirt.Length != 0) {
        AvatarShirt = other.AvatarShirt;
      }
      if (other.AvatarPants.Length != 0) {
        AvatarPants = other.AvatarPants;
      }
      if (other.AvatarHat.Length != 0) {
        AvatarHat = other.AvatarHat;
      }
      if (other.AvatarShoes.Length != 0) {
        AvatarShoes = other.AvatarShoes;
      }
      if (other.AvatarEyes.Length != 0) {
        AvatarEyes = other.AvatarEyes;
      }
      if (other.AvatarBackpack.Length != 0) {
        AvatarBackpack = other.AvatarBackpack;
      }
      if (other.AvatarGloves.Length != 0) {
        AvatarGloves = other.AvatarGloves;
      }
      if (other.AvatarSocks.Length != 0) {
        AvatarSocks = other.AvatarSocks;
      }
      if (other.AvatarBelt.Length != 0) {
        AvatarBelt = other.AvatarBelt;
      }
      if (other.AvatarGlasses.Length != 0) {
        AvatarGlasses = other.AvatarGlasses;
      }
      if (other.AvatarNecklace.Length != 0) {
        AvatarNecklace = other.AvatarNecklace;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 16: {
            Skin = input.ReadInt32();
            break;
          }
          case 24: {
            Hair = input.ReadInt32();
            break;
          }
          case 32: {
            Shirt = input.ReadInt32();
            break;
          }
          case 40: {
            Pants = input.ReadInt32();
            break;
          }
          case 48: {
            Hat = input.ReadInt32();
            break;
          }
          case 56: {
            Shoes = input.ReadInt32();
            break;
          }
          case 64: {
            Avatar = input.ReadInt32();
            break;
          }
          case 72: {
            Eyes = input.ReadInt32();
            break;
          }
          case 80: {
            Backpack = input.ReadInt32();
            break;
          }
          case 90: {
            AvatarHair = input.ReadString();
            break;
          }
          case 98: {
            AvatarShirt = input.ReadString();
            break;
          }
          case 106: {
            AvatarPants = input.ReadString();
            break;
          }
          case 114: {
            AvatarHat = input.ReadString();
            break;
          }
          case 122: {
            AvatarShoes = input.ReadString();
            break;
          }
          case 130: {
            AvatarEyes = input.ReadString();
            break;
          }
          case 138: {
            AvatarBackpack = input.ReadString();
            break;
          }
          case 146: {
            AvatarGloves = input.ReadString();
            break;
          }
          case 154: {
            AvatarSocks = input.ReadString();
            break;
          }
          case 162: {
            AvatarBelt = input.ReadString();
            break;
          }
          case 170: {
            AvatarGlasses = input.ReadString();
            break;
          }
          case 178: {
            AvatarNecklace = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
