// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Data/Player/PlayerAvatarType.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Data.Player {

  /// <summary>Holder for reflection information generated from POGOProtos/Data/Player/PlayerAvatarType.proto</summary>
  public static partial class PlayerAvatarTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Data/Player/PlayerAvatarType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerAvatarTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1QT0dPUHJvdG9zL0RhdGEvUGxheWVyL1BsYXllckF2YXRhclR5cGUucHJv",
            "dG8SFlBPR09Qcm90b3MuRGF0YS5QbGF5ZXIqRAoQUGxheWVyQXZhdGFyVHlw",
            "ZRIWChJQTEFZRVJfQVZBVEFSX01BTEUQABIYChRQTEFZRVJfQVZBVEFSX0ZF",
            "TUFMRRABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Data.Player.PlayerAvatarType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum PlayerAvatarType {
    [pbr::OriginalName("PLAYER_AVATAR_MALE")] PlayerAvatarMale = 0,
    [pbr::OriginalName("PLAYER_AVATAR_FEMALE")] PlayerAvatarFemale = 1,
  }

  #endregion

}

#endregion Designer generated code
